name: Build & Release

on:
  push:
    branches: [ "master"]
  workflow_dispatch:

jobs:
  Build_Release:
    runs-on: [ self-hosted, linux, latex ]
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Update LaTeX
        id: update
        continue-on-error: true
        shell: bash
        run: tlmgr update --all

      - name: Compile LaTeX document
        id: compile
        shell: bash
        run: |
          cd src/
          rm -rf /build
          mkdir /build
          # compile the main file
          pdflatex -quiet -shell-escape -synctex=1 -interaction=nonstopmode -file-line-error -output-directory /build/ main.tex > /dev/null 2>&1 || true
          echo "First build done"
          # compile againg because Latex is strange
          pdflatex -quiet -shell-escape -synctex=1 -interaction=nonstopmode -file-line-error -output-directory /build/ main.tex > /dev/null 2>&1 || true
          echo "Second build done"
          # compile a third time so we can finally have the index
          pdflatex -quiet -shell-escape -synctex=1 -interaction=nonstopmode -file-line-error -output-directory /build/ main.tex > /dev/null 2>&1 || true
          echo "Third build done"
          mv /build/main.pdf /build/Appunti-LFC.pdf

      - name: Upload Log
        id: uplaodLog
        uses: actions/upload-artifact@v3
        with:
          name: Logs
          path: /build/main.log
          if-no-files-found: warn
          
      - name: Publish Release
        id: release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /build/Appunti-LFC.pdf
          asset_name: Appunti-LFC.pdf
          overwrite: true
          body: "Appunti di Linguaggi Formali e Compilatori - Prof.ssa P. Quaglia - Università di Trento"
          release_name: "Appunti di Linguaggi Formali e Compilatori"
